name: Sync Docker Images

on:
  workflow_dispatch:
    inputs:
      provider:
        description: 'Provider to use (aliyun/huawei)'
        required: true
        default: 'aliyun'
      image_list_file:
        description: 'Path to the image list file'
        required: true
        default: 'images.txt'
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

env:
  IMAGE_LIST_FILE: ${{ github.event.inputs.image_list_file || 'images.txt' }}
  PROVIDER: ${{ github.event.inputs.provider || 'aliyun' }}

jobs:
  sync:
    name: Sync to ${{ github.event.inputs.provider || 'aliyun' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install skopeo
        run: |
          curl -sL https://github.com/lework/skopeo-binary/releases/download/v1.14.2/skopeo-linux-amd64 -o /usr/local/bin/skopeo
          chmod +x /usr/local/bin/skopeo
          skopeo --version

      - name: Get dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build
        run: |
          BUILD_TIME=$(date +%Y-%m-%d_%H:%M:%S)
          go build -ldflags "-X main.BuildTime=$BUILD_TIME" -o sync ./cmd/sync

      - name: Run sync
        env:
          PROVIDER: ${{ env.PROVIDER }}
          IMAGE_LIST_FILE: ${{ env.IMAGE_LIST_FILE }}
          ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
          ALIYUN_NAMESPACE: ${{ secrets.ALIYUN_NAME_SPACE }}
          ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
          ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
          HUAWEI_REGISTRY: ${{ secrets.HUAWEI_REGISTRY }}
          HUAWEI_NAMESPACE: ${{ secrets.HUAWEI_NAMESPACE }}
          HUAWEI_REGISTRY_USER: ${{ secrets.HUAWEI_REGISTRY_USER }}
          HUAWEI_REGISTRY_PASSWORD: ${{ secrets.HUAWEI_REGISTRY_PASSWORD }}
        run: ./sync

      # - name: Send email notification
      #   if: always()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.163.com
      #     server_port: 465
      #     username: ${{ secrets.EMAIL_USERNAME }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     subject: Docker镜像同步完成通知
      #     to: ${{ secrets.EMAIL_USERNAME }}
      #     from: GitHub Actions
      #     body: |
      #       Docker镜像同步完成
